spring:
  application:
    name: config-server
 #git配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HangStarLi/config-server
          username: 1838705553@qq.com
          password: hang122333
server:
  port: 9100
#指定注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#git配置